### ISSUE TITLE
Feature Request: Link Metadata

### ISSUE THREAD

**Issue by NeonReactionary** [org-roam/org-roam-ui#24]
# Is Your Feature Request Related To A Problem? Please Describe.
With notes often having many branches to other notes in many different contexts, it can be difficult to relate data in a meaningful way, understand what relevance certain links may have had, or simply be lost in a glut of links.

# Describe The Solution You'd Like
Some additional fields for link metadata. This could be useful if one wanted to expand the depth of a network, but filter for certain conceptual links across wider regions of the networks. In other words, this can be used to capture wider bodies of knowledge or research themes.

for example:
[[\<link id>][\<link title>][:tags \<tag> :context \<short description>]]

# Describe Alternatives You've Considered
A link-note that contains all the information as a separate entity. This could be viewed as a pop-up by hovering over the link and provide additional context.

# Additional Context
Links between notes are almost as important as the notes themselves. There should be some kind of additional features that reflect this.

**Comment by ThomasFKJorna** [comment]
I think this is a great idea and one which I've also considered myself, and luckily react-force-graph has built in support for this kind of thing. The problem lies more in collecting that data, which org-roam does for us. If someone were to write a plugin for org-roam which adds this kind of information to the database we'd happily support this, but I don't see us doing this ourselves anytime soon. I'll convert this issue to a discussion as I'd be interested to hear what other think of this!
