### ISSUE TITLE
Display graph and text side by side

### ISSUE THREAD

**Issue by izzues** [org-roam/org-roam-ui#52]
Thanks for the great work!

I'm new to Emacs, so I apologize for the newbie question.

When I start up org-roam-ui, a browser window opens. How do I make the graph appear in Emacs itself, in the same window as the file I'm editing?

Thanks!

**Comment by ThomasFKJorna** [comment]
There are two ways (that I know of) how to do this (assuming with "Window" you mean what Emacs confusingly calls a "frame", which is the thingy with the close button etc):
1. Use a version of Emacs compiled with XWidgets support. Frankly, i don't really know how to do this, maybe ask @shaunsingh since he seems to be using it.
2. Use the (Emacs Application Framework)[https://github.com/manateelazycat/emacs-application-framework] to open a browser tab inside Emacs and place it wherever you like. This does not work if you are using the PGTK branch of Emacs! (if you don't know what that is, you probably don't have it)

Truth be told, I would love for there to be some easy way to display ORUI in Emacs, but that does not seem to be possible yet. :( 
We are working on PWA support, which would mean you could install the ORUI as a separate app, but this is not working at the moment.

Hope that helped!

**Comment by ThomasFKJorna** [comment]
Thanks for the writeup! Thank you so much for alerting me to the fact that that AUR version comes with xwidgets support!!!   I've been using it since early this year probably and did not even know that was on by default, this is fantastic and all I ever wanted!

![image](https://user-images.githubusercontent.com/21983833/128896507-ba5c7a49-a61b-4cc8-a4bb-d8afac2eb1bc.png)

Having an integrated solution is so much nicer than having to open a separate program. It is noticeably slower than Chromium or Firefox (shocker) but for local mode it's more than doable. I like this so much in fact that I'm thinking of making it the default behavior (granted that you have xwidget support), as you can always open it somewhere else.

Pro-tip: you don't need to set xwidgets to your default browser, either just go to the relevant url with `xwidget-webkit-browse-url` or do 
```emacs-lisp
(setq org-roam-ui-browser-function #`xwidget-webkit-browse-url)
```

**Comment by ThomasFKJorna** [comment]
Dumb question though: how do you zoom :thinking:

**Comment by ThomasFKJorna** [comment]
Having it as the default might not be a good idea though, I have no idea what functions Webkit does or does not support. TS should compile it to a reasonable target, but still.

**Comment by hyan46** [comment]
To add on, I am using mac and I use [`emacs-plus`](https://github.com/d12frosted/homebrew-emacs-plus) and `--with-xwidgets` to build with xwidget support by default so it is easy for me to set this up following @shaunsingh's method. 

Currently, the only problem I have with this setup is that when I click the node that it opens the node in the current xwidget buffer, not the buffer next to it so every time it replaces the graph. It would be nice if there is any way of openning the node buffer next to the graph buffer. 

I have not yet tried the EAF yet, may also explore to see what behavior it has.

**Comment by ThomasFKJorna** [comment]
Good to hear it's also possible on Mac! I doubt that behavior would change in EAF, as that's simply the default behavior org-roam-ui has, as it's designed to be used in a regular browser, where that behavior would result in opening another tab, which I personally would find incredibly annoying.
We could add that feature, but more than that we will have to think about how we want ORUI to behave in general. I still mostly envision it as a standalone webapp, as most people will probably use it as such, which would mean that new windows would just be new things in the current org-roam-ui tab (or window, when we get PWA support working).

However, having it be more modular would also be cool, as that would bring Emacs a bit closer to how other editors such as Obsidian behave, which is good I think.

**Comment by ThomasFKJorna** [comment]
I consider this fixed, but we need to update the docs before we close it.

**Comment by greghab** [comment]
On EXWM, every frame, including X-applications is managed by Emacs, so you're browser will always get replaced by the note you click on from the graph. Only way around that is to do a split, and then `float your browser` over that split (on top of, and ignoring emacs's frame management) to keep it at a given location. But then you get `teleported` to a different workspace, with the note opened up there. I tried doing a split at that workspace it chose for me, and tried it again to see if it would stay in the same place after a layout modification. But it picked a workspace I hadn't touched, and put the note there, and teleported me there instead. **So in EXWM, you can't use this thing in any reasonable way.**

**Comment by ThomasFKJorna** [comment]
Hmm yes, this also happens when you have a webkit window open and try to open a note: it replaces itself. The solution would probably be to check whether you are using webkit or exwm, and then open a new window instead of the replacing the current buffer. I don't have time to look into this right now, but I will fix it eventually, could you make a new issue for this?

**Comment by greghab** [comment]
@ThomasFKJorna done.

**Comment by greghab** [comment]
If you want to accomplish this today, use linux and a tiling window manager (like i3, or sway). Do a split on emacs, and float your browser (get it out of tiling mode, so that you can move it around freely and it will appear on top of everything, including emacs), and position and resize it over a part of the split. If you click on a given opened org note, and then go to the browser and click on a given node in the graph, it will open it up in the location of that prior note you were on. (So if I was on "Test Node", then clicked on the graph, it will open it up where "Test Node" is).
In `i3-wm`, to float the browser you can do something like this:
```
# toggle tiling / floating
bindsym $mod+Shift+space floating toggle
```

![image](https://user-images.githubusercontent.com/7407672/131931934-ada4207c-6493-4556-9f11-f98d2f0845f1.png)

**Comment by shaunsingh** [comment]
I'm actually using sway (with nyxt) now, and with some elisp hackery it works quite well! I disabled inner-borders with sway too, so it looks like its in a split (even though its not)

I found xwidgets pretty slow as my graph became bigger and bigger. Something blink-based feels much faster and fluent. Still, if anyone wants here's a little snippet I have to automatically have xwidgets open it in a vertical popup window. 

Note that theres a bug with xwidgets where it doesn't represent popup rules, so on some configs it might open vertically instaed of horizontally. 

```lisp
(defcustom org-roam-ui-use-webkit t
  "Use embedded webkit to preview.
This requires GNU/Emacs version >= 26 and built with the `--with-xwidgets`
option."
  :type 'boolean
  :group 'roam)

(defun org-roam-ui-browser (url)
  "Use browser specified by user to load URL.
Use default browser if nil."
  (if org-roam-ui-url-browser
      (let ((browse-url-generic-program org-roam-ui-url-browser)
            (browse-url-generic-args roam-url-args))
        (ignore browse-url-generic-program)
        (ignore browse-url-generic-args)
        (browse-url-generic url))
    (browse-url url)))

(defun org-roam-ui-open-url (url)
  "Ask the browser to load URL.
Use default browser unless `xwidget' is available."
  (if (and org-roam-ui-use-webkit
           (featurep 'xwidget-internal))
      (progn
        (xwidget-webkit-browse-url url)
        (let ((buf (xwidget-buffer (xwidget-webkit-current-session))))
          (when (buffer-live-p buf)
            (and (eq buf (current-buffer)) (quit-window))
            (let (display-buffer-alist)(pop-to-buffer buf)))))
    (org-roam-ui-browser url)))

;;;###autoload
(define-minor-mode org-roam-ui-open-in-browser
  "open org-roam-ui in the browser"
 :lighter "roam"
 (org-roam-ui-open-url "http://127.0.0.1:35901"))
```
