### ISSUE TITLE
Literature note labels show up wrong

### ISSUE THREAD

**Issue by thriveth** [org-roam/org-roam-ui#56]
In my graph, literature nodes created with org-roam-bibtex are labeled with placeholders for author or title in front of the note title, as shown on this screenshot. 

![image](https://user-images.githubusercontent.com/1553566/128750242-8751a924-5377-4acb-a822-9b2a5050b100.png)

I also notice that it incorrectly corrects all-uppercase words to lowercase (the title of the note is "C III] Emission in Star-forming Galaxies Near and Far").

**Comment by ThomasFKJorna** [comment]
There are three-ish things that usually go wrong here.
1. Org-roam-bibtex is not loaded
2. You are not running the latest version of org-roam-ui
3. You are using emacs < 27.1

The main problem is that you `orb-prefactor-keywords` does not contain `author-abbrev` or `year`, which probably means you are setting it manually as these are included in the defaults.

This is our bad, because it should either just work or not do this, but atm it's like an inbetween thing. 
If none of the above help, disable `org-roam-ui-retitle-ref-nodes`. Sorry for the inconvenience!

We should iron out this behavior a bit more @blester125. Either make it opt in (probably the best option), requiring orb to make sure it's loaded or move that check to the place you suggested. I don't think the problem is with the template defaults per se, as these are the default values orb gives it, and if people are setting it so something custom anyway we can't depend on anything. I will try to fix this.

**Comment by ThomasFKJorna** [comment]
Latest commit should fix this for real for real.

**Comment by ThomasFKJorna** [comment]
Fun fact: if you mention an issue in your commit, it automatically closes it! Neat

**Comment by thriveth** [comment]
Wow @ThomasFKJorna, fast and efficient as always! 

In my case, ORB is definitely loaded, I am using Emacs 27.2, and I updated org-roam-ui a few days ago but much might have happened in the meantime. 

But my ref notes are made perhaps half a year ago and might be missing stuff that ORB does include these days. Could be it. 

I'll try and pull the latest ORUI and see if it is fixed!

**Comment by thriveth** [comment]
Update: With a freshly pulled ORUI, the node shows up simply as its cite key. 
How should I format the note to make it look nicer?

**Comment by thriveth** [comment]
Also - sorry for spamming this thread - with the latest update, it looks like the graph doesn't get the information it needs from Emacs anymore? Follorwing doesn't work, and neither does highlighting the node currently focused in Emacs.

**Comment by ThomasFKJorna** [comment]
No worries! Are you sure "org-roam-ui-follow-mode" is running?

**Comment by thriveth** [comment]
Org-roam-follow-mode is indeed running, yes. 

I tried checking out older commits, the last one before follow-mode breaks for me is e71c0afd6e2bebfc0a9b0273c80bab8cf1ad0181 . 

Should I open a new issue for this?

**Comment by ThomasFKJorna** [comment]
Yes please!
