### ISSUE TITLE
Preview mode

### ISSUE THREAD

**Issue by SYNTAXDZ** [org-roam/org-roam-ui#64]
Hi, does org-roam-ui support **preview-mode** when you hover a node like org-roam-server ?

**Comment by Hellseher** [comment]
Hi @SYNTAXDZ If you check [README](https://github.com/org-roam/org-roam-ui/tree/main#planned-features) there is a list with planned features, and file viewer is not implemented yet.

**Comment by SYNTAXDZ** [comment]
ok, thanks for your reply

**Comment by ThomasFKJorna** [comment]
That is correct, file viewer-like capabilities will be implemented in the future!

**Comment by ThomasFKJorna** [comment]
Explanation for the delay: 
We will add this in the future. One of the branches has a rather shoddy implementation, but we have not incorporated that into the main one and most likely won't any time soon. We would like to not rely on Emacs to convert your org-files to HTML and instead use an AST parser like Orga or Uniorg. However, these packages are in a bit of a pickle atm because the Unified framework they build upon just changed to ES modules a couple of weeks ago and they will need to adapt. We will wait until they do or we find a suitable workaround, but it will take a bit.

**Comment by rasendubi** [comment]
I have tried to convert Uniorg to ESM-only before but that failed because the unified ecosystem itself didn’t finish the migration at the time and I’ve hit a couple of bugs here and there. It looks like it’s done now (https://github.com/unifiedjs/unified/issues/121#issuecomment-899497157), so I might try again somewhen this month.

This will require changes to org-roam-ui though because you cannot import ESM from a commonjs module (https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). Also, ESM support in nextjs is still experimental (https://nextjs.org/blog/next-11-1#es-modules-support).

If you need a workaround, the easiest option is to pin unified packages to the previous major version. e.g., `npm install unified@9 vfile@4` etc

**Comment by ThomasFKJorna** [comment]
I have gotten OrgaJS working in the meantime, so this option is now definitely on the table. I've been very busy with other things lately so I haven't tried implementing it yet, but will in the foreseeable future!

If you have any ideas on what kind of behavior you would like to see please let me know! The UX part of this is much more difficult than the software part

**Comment by rasendubi** [comment]
kk. If you need any help with getting the software part of Uniorg working though (getting it up and running, fixing any bugs, or implementing missing features), just ping me—I am more than willing to help.

(I am the author of the uniorg so I am obviously biased here, but the very reason I started it is that orga is a lousy org parser. When I used it for my website, it failed to parse lists correctly and thrown exceptions on ~10% of my pages.)

**Comment by ThomasFKJorna** [comment]
Ah I see, I didn't notice you were the one who wrote uniorg! I indeed had similar trouble getting uniorg to work, but I think that was mostly due to not having the package pinned. 

I have no horse in this race, but I would of course prefer accurate parsing over... well, not that. What 10% did you notice Orga missing? Were they some specific Org features or was it just a general error margin? Given that you went through the trouble of writing an entire parser yourself because of this inaccuracy, I think it would be wise of me to consider that haha

**Comment by rasendubi** [comment]
> What 10% did you notice Orga missing? Were they some specific Org features or was it just a general error margin?

Cannot attribute this to any specific org feature but when I ran Orga on all my notes, it just failed to parse some portion of them (thrown exception = no output). On many other notes, it produced incorrect results (mostly bad handling of lists with nested indentation, quotes, etc.).

I don’t want to sound picky but I just put the first random note from my org-roam into [orga playground](https://orga.js.org/playground/?text=%3APROPERTIES%3A%0A%3AID%3A%20%20%20%20%20%20%20114b54b3-ff48-445a-bd7c-4f3f601b49e5%0A%3AEND%3A%0A%23%2BTITLE%3A%20Layered%20programming%0A-%20tags%20%3A%3A%20%5B%5Bid%3Ae8f467e3-f580-4adf-a226-e12015a49699%5D%5B%C2%A7%20Programming%5D%5D%0A-%20source%20%3A%3A%20%5B%5Bhttp%3A%2F%2Fakkartik.name%2Fpost%2Fwart-layers%5D%5BA%20new%20way%20to%20organize%20programs%5D%5D%20in%20%5B%5Bid%3A9f5cab01-45d0-4b63-8fec-d7adbec72c9c%5D%5BKartik%20Agaram%5D%5D's%20blog%0A%0AThe%20idea%20of%20the%20layered%20programming%20is%20to%20compose%20the%20program%20from%20%22layers%22%20of%20code%2C%20where%20the%20first%20layers%20lay%20out%20the%20foundations%20and%20subsequent%20layers%20could%20add%20more%20features.%20The%20cool%20thing%20about%20this%20paradigm%20is%20that%20it%20allows%20better%20understanding%20of%20the%20application%2C%20because%20newcomers%20could%20understand%20the%20core%20of%20the%20system%20from%20the%20first%20layer%20and%20then%20gradually%20learn%20more%20features%20by%20exploring%20each%20layer.%20They%20could%20even%20build%20and%20run%20the%20application%20with%20some%20layers%20disabled%2C%20etc.%0A) and it couldn’t even parse the file properties drawer.

Here is an example of [some other issues with Orga](https://orga.js.org/playground/?text=%3APROPERTIES%3A%0A%3AID%3A%20%20%20this-is-id%0A%3AEND%3A%0A*%20Issues%20with%20lists%0A%0AOne%20empty%20line%20in%20the%20middle%20of%20an%20item%20messes%20the%20list%20completely%3A%0A%0A1.%20list%201%0A%20%20%201.%20world%0A%0A%20%20%202.%20list%202%3F%0A2.%20list%203%3F%3F%0A3.%20item%203%0A%0A%20%20%20item%203%20continues%3F%0A4.%20item%0A%20%20%20%23%2Bbegin_src%20fundamental%0A%20%20%20hello%0A%20%20%20%23%2Bend_src%0A%0AThis%20should%20have%20been%20a%20top-level%20paragraph%20but%20it%20is%20not.%20(Because%20of%20src%20block%20before%3F)%0A%0A-%20this%20must%20be%20a%20new%20top-level%20list%0A%0A**%20a%20headline%20nested%20inside%20a%20list%3F%3F%0A%0A*%20Reset%0ATags%20are%20not%20parsed%20in%20lists%3A%0A-%20%5B%5Bhttps%3A%2F%2Fexample.com%5D%5BExample%5D%5D%20%3A%3A%20Hello%20there!%0A-%20%5B%5Bhttps%3A%2F%2Fgithub.com%5D%5BGitHub%5D%5D%20%3A%3A%20This%20is%20GitHub%2C%20your%20hub%20for%20Git%20repos.%0A-%20*Gitlab*%20%3A%3A%20Alternative%20to%20GitHub%0A-%20%2FSourcehut%2F%20%3A%3A%20Another%20alternative%20to%20GitHub%20that%20primarily%20uses%20email-based%20workflows.%0A-%20%2FCodeberg%2F%20%3A%3A%20*ANOTHER%20ALTERNATIVE*%0A-%20%2F*self-hosting%20Git%20server*%2F%20%3A%3A%20%2F*The%20ultimate%20Git%20solution%20for%20privacy-oriented%20individuals!*%2F%0A%0A*%20Missing%20support%0A**%20Fuzzy%20links%0Ano%20fuzzy%20links%3A%20https%3A%2F%2Fexample.com%2F%0A%0A**%20Escapers%20in%20src%20block%0ANo%20escapers%20in%20src%20block%3A%0A%23%2Bbegin_src%20c%0A%2C*a%20%3D%200%3B%0A%23%2Bend_src%0A%0A**%20superscript%2Fsubscript%0A-%20hello%5Eworld%0A-%20H_2%0A%0A**%20fixed-width%0A%3A%20hello%0A%3A%20world%0A%0A**%20LaTeX%0A%5Cbegin%7Bequation%7D%0Aa%20%2B%20b%0A%5Cend%7Bequation%7D%0A%0AInline%20latex%3A%20%24%24a%20%2B%20b%24%24). (You can try the same example in [Uniorg playground](https://www.alexeyshmalko.com/uniorg/) for comparison.)

<details>
<summary>Org-mode source</summary>

```
:PROPERTIES:
:ID:   this-is-id
:END:
* Issues with lists

One empty line in the middle of an item messes the list completely:

1. list 1
   1. world

   2. list 2?
2. list 3??
3. item 3

   item 3 continues?
4. item
   #+begin_src fundamental
   hello
   #+end_src

This should have been a top-level paragraph but it is not. (Because of src block before?)

- this must be a new top-level list

** a headline nested inside a list??

* Reset
Tags are not parsed in lists:
- [[https://example.com][Example]] :: Hello there!
- [[https://github.com][GitHub]] :: This is GitHub, your hub for Git repos.
- *Gitlab* :: Alternative to GitHub
- /Sourcehut/ :: Another alternative to GitHub that primarily uses email-based workflows.
- /Codeberg/ :: *ANOTHER ALTERNATIVE*
- /*self-hosting Git server*/ :: /*The ultimate Git solution for privacy-oriented individuals!*/

* Missing support
** Fuzzy links
no fuzzy links: https://example.com/

** Escapers in src block
No escapers in src block:
#+begin_src c
,*a = 0;
#+end_src

** superscript/subscript
- hello^world
- H_2

** fixed-width
: hello
: world

** LaTeX
\begin{equation}
a + b
\end{equation}

Inline latex: $$a + b$$
```

</details>

**Comment by ThomasFKJorna** [comment]
Wow thank you for the extensive demonstration! Those are indeed quite some issues, the LaTeX one is really big for me as I use it extensively throughout my notes (although this can apparently be solved by using a unified plugin in Orga, https://github.com/orgapp/orgajs/issues/41).

I guess the main worry I had with uniorg was speed, but (even though this isn't a fair comparison because it's based on the implementation etc) your playground parsed my  10k+ words document with a ton of LaTeX faster and obviously much more accurately than on Orga, so I'm sold!  The only upside I now see for Orga is it's ability to render JSX from Org files, which, while cool, I don't see a clear usecase for right now.

I will try to get Uniorg working, thanks for your detailed exposition! :)

**Comment by ThomasFKJorna** [comment]
It's here!
