### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by KjartanOli** [org-roam/org-roam-ui#77]
**Describe the bug**
Every time I try to open the UI, I'm sent straight to a 404 Not Found page.

**To Reproduce**
1. Activate org-roam-ui-mode
2. Watch browser open
3. See a 404 Not Found page

**Expected behavior**
Org-Roam UI opens.

**What browser were you using?**
So far I've reproduced this on both Firefox, and Nyxt, which I believe uses WebKit. 

**Additional context**
I'm running Emacs 28.0.50, compiled from git://git.savannah.gnu.org/emacs.git, with Spacemacs. I installed `org-roam-ui` with `quelpa-usepackage`
```lisp
(use-package org-roam-ui :quelpa (org-roam-ui :fetcher github :repo "org-roam/org-roam-ui"))
```

**Comment by ThomasFKJorna** [comment]
You should look at the installation instruction in the Readme for use-package. You aren't requiring the most important part: the javascript! 

To do so, add this after `repo:org-roam-ui`

```
:files ("*.el" "out")
```

We should probably add this recipe to use with quelpa instead of straight (I'm not even sure those are mutually exclusive, I'm too spoiled by Doom-emacs).
