### ISSUE TITLE
[BUG] Maybe bug of linking children to parents heading

### ISSUE THREAD

**Issue by MountainsUsual** [org-roam/org-roam-ui#87]
**Describe the bug**

**To reproduce**
To illustrate this problems, I just created a new file and create 12-level headings, and use org-id-get-create to create id for those headings. And I save this file and turn to the webpage. And I get the result showed in the screenshot.

**Expected behavior**
I intuitively think that the children node will link to parents node one level higher rather than all link to Level1.

**Screenshots**
![heading_level_bug](https://user-images.githubusercontent.com/33800203/132982769-d8193f75-6d37-418d-9ca9-e9553b5edbef.png)

**What browser were you using?**
MS Edge

Thanks for reading!

**Comment by ThomasFKJorna** [comment]
Hmm yes that should indeed not be the case.

**Comment by ThomasFKJorna** [comment]
![image](https://user-images.githubusercontent.com/21983833/132992139-62cde0cc-b317-4440-95cd-5a391a5b279a.png)

Indeed also does not work properly for me, I'll investigate!

**Comment by MountainsUsual** [comment]
Thanks a lot for your investigation and contribution! I will upgrade tomorrow and try it. Wish all the best!

**Comment by ThomasFKJorna** [comment]
Okay I fixed it, it should work how you expect it to now. Unfortunately this reintroduces (or rather, exposes that it was never fixed in the first place) #67, specifically in the following case. If you have an id-having heading with the same title as a non-id-having parent-heading of a node, the node will link to the id-having heading when it should not.

* Heading 1 :has-id
* * Heading 2 :has-id
* * Heading 2 :does-not-have-id
* ** Heading 3 :has-id

Heading 3 will now link to Heading 2 :has-id while it should link to heading 1. 
There is way around this behavior now except for doing what was proposed before: doing a big SQL query and looping over the actual files. The org-roam-db simply does not provide the information to discern whether or not Heading 2 :has-id should be linked to.

I think this is a rather niche case, and if you are mixing same-named headings with having/not-having an id, you are not making things easy for yourself anyway. :p

**Comment by ThomasFKJorna** [comment]
This also encouraged me to finally fix the highlighting issue with these parent nodes (they would always highlight both the parent-file and parent-heading nodes). Let me know if this also works how you would expect it to!
